AWSTemplateFormatVersion: "2010-09-09"
Description: Graphite Test Suite Target Table
Resources:

  Table:
    Type: "AWS::DynamoDB::Table"
    DeletionPolicy: Retain
    Properties:
      TableName: graphite-library-test
      KeySchema:
        - AttributeName: origin
          KeyType: HASH
        - AttributeName: typeTarget
          KeyType: RANGE
      AttributeDefinitions:
        - AttributeName: origin
          AttributeType: S
        - AttributeName: target
          AttributeType: S
        - AttributeName: typeOrigin
          AttributeType: S
        - AttributeName: typeTarget
          AttributeType: S
        - AttributeName: secondary
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      GlobalSecondaryIndexes:
        - IndexName: InByPrimary
          KeySchema:
            - AttributeName: target
              KeyType: HASH
            - AttributeName: typeOrigin
              KeyType: RANGE
          Projection:
            ProjectionType: INCLUDE
            NonKeyAttributes:
              - secondary
              - stash
        - IndexName: OutBySecondary
          KeySchema:
            - AttributeName: typeOrigin
              KeyType: HASH
            - AttributeName: secondary
              KeyType: RANGE
          Projection:
            ProjectionType: INCLUDE
            NonKeyAttributes:
              - target
              - stash
        - IndexName: InBySecondary
          KeySchema:
            - AttributeName: typeTarget
              KeyType: HASH
            - AttributeName: secondary
              KeyType: RANGE
          Projection:
            ProjectionType: INCLUDE
            NonKeyAttributes:
              - origin
              - stash
      TimeToLiveSpecification:
        AttributeName: expiresAt
        Enabled: true