AWSTemplateFormatVersion: "2010-09-09"
Description: Graphite Test Suite Target Table
Resources:

  Table:
    Type: "AWS::DynamoDB::Table"
    DeletionPolicy: Retain
    Properties:
      TableName: graphite-library-test
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: origin
          AttributeType: S
        - AttributeName: target
          AttributeType: S
        - AttributeName: edgeOrigin
          AttributeType: S
        - AttributeName: edgeTarget
          AttributeType: S
        - AttributeName: secondary
          AttributeType: S

      # "OutByPrimary" via Table Key
      KeySchema:
        - AttributeName: origin
          KeyType: HASH
        - AttributeName: edgeTarget
          KeyType: RANGE

      GlobalSecondaryIndexes:

        - IndexName: InByPrimary
          KeySchema:
            - AttributeName: target
              KeyType: HASH
            - AttributeName: edgeOrigin
              KeyType: RANGE
          Projection:
            ProjectionType: INCLUDE
            NonKeyAttributes:
              - stash

        - IndexName: OutBySecondary
          KeySchema:
            - AttributeName: origin
              KeyType: HASH
            - AttributeName: edgeSecondary
              KeyType: RANGE
          Projection:
            ProjectionType: INCLUDE
            NonKeyAttributes:
              - stash

        - IndexName: InBySecondary
          KeySchema:
            - AttributeName: target
              KeyType: HASH
            - AttributeName: edgeSecondary
              KeyType: RANGE
          Projection:
            ProjectionType: INCLUDE
            NonKeyAttributes:
              - stash

      TimeToLiveSpecification:
        AttributeName: expiresAt
        Enabled: true